name: Test

on:
    - push
    - pull_request

defaults:
    run:
        shell: bash

jobs:
    pytest:
        strategy:
            fail-fast: true
            matrix:
                os:
                    - ubuntu-latest
                    - windows-latest
                python-version:
                    - "3.9"
                    - "3.10"
                    - "3.11"
                    - "pypy-3.9"
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install test dependencies
              run: pip install tox tox-gh-actions pyserial pytest intelhex
            - name: Run setup and tests as defined in tox.ini
              run: tox
